### ISSUE TITLE
code review issues 

### ISSUE THREAD

**Issue by ReAliens** [rdnrn/capstone-summit#1]
Good work Nana :100: :1st_place_medal: :smile:  
You did amazing design implementation but here are a few suggestions to enhance your project 
1- more button should work properly because it doesn't work right now.
2- main program cards should be at the same width 
3- the header topics should be justified to right more as displayed in the design 

cheers Nana

**Comment by imubarak234** [comment]
Good job so far

**Comment by KayLemba** [comment]
Hello Nana Good Job so far. I have a few suggestions to help you make you project look outstanding. 😄       

<span>2021.10.15(THU) ~ 16(FRI)</span>
        <div class="place">
          @ Middle of Nowhere
        </div>

 1. Please add a font-weight to the section above to bolden the font so its more visible.
 2. Second suggestion try and make you background image more visible on the home page.

Happy Coding 😄 
cheers 🍾

**Comment by arnrdn** [comment]
Thank you all for your suggestions! 😄
